stages:
  - build
  - push
build:
  stage: build
  script:
    - docker build -t registry.github.com/herisulistiyanto/gitlab-ci-android/android:latest .
push:
  stage: push
  script:
    - docker push registry.github.com/herisulistiyanto/gitlab-ci-android/android:latest

